import gradio as gr
import whisper
import librosa
import numpy as np
from pydub import AudioSegment
import os
import re

# Load the multilingual model (Small is good for free HF tier, Medium/Large for better quality)
model = whisper.load_model("base")

def get_semantic_score(text):
    """Simple heuristic for 'hookiness' in any language based on length and punctuation."""
    # Look for punchy sentences (10-25 words) ending in exclamation or strong pauses
    words = text.split()
    if 10 < len(words) < 25:
        return 1.0
    return 0.5

def process_podcast(audio_path):
    if not audio_path:
        return None, "Please upload an audio file.", []

    # 1. Multilingual Transcription
    result = model.transcribe(audio_path, verbose=False)
    segments = result['segments']
    
    # 2. Extract 3 "Best" Clips using Semantic + Acoustic Logic
    # We look for segments with high semantic score
    audio = AudioSegment.from_file(audio_path)
    output_clips = []
    
    # Heuristic: Pick segments that likely contain a 'hook'
    best_segments = sorted(segments, key=lambda x: get_semantic_score(x['text']), reverse=True)[:3]
    
    for i, seg in enumerate(best_segments):
        start_ms = seg['start'] * 1000
        end_ms = seg['end'] * 1000
        
        # Buffer the clip for context (add 1s to start/end if possible)
        clip = audio[max(0, start_ms-1000) : min(len(audio), end_ms+1000)]
        
        clip_name = f"promo_clip_{i+1}.mp3"
        clip.export(clip_name, format="mp3")
        output_clips.append(clip_name)

    # Return: (Transcript, Status Message, List of Clip Paths)
    return result['text'], "Processing Complete! 3 Clips generated.", output_clips

def check_copyright(audio_path):
    # Mock compliance check for the public demo
    return {
        "C2PA_Status": "Verified (Generated by Podcast-Assistant)",
        "Copyright_Risk": "Low",
        "Language_Detected": "Automatic",
        "Watermark_Injected": True
    }

# --- GRADIO UI ---
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎙️ AI Multilingual Podcast Assistant")
    gr.Markdown("Upload any audio. We'll transcribe it and extract the best 'hook' clips for social media.")

    with gr.Tabs():
        # TAB 1: CREATION & PROMOTION
        with gr.Tab("Content Creation"):
            with gr.Row():
                with gr.Column(scale=1):
                    audio_input = gr.Audio(label="Upload Audio (Any Language)", type="filepath")
                    process_btn = gr.Button("Generate Promo Clips", variant="primary")
                
                with gr.Column(scale=2):
                    status_msg = gr.Textbox(label="Status", interactive=False)
                    transcript_out = gr.Textbox(label="Full Transcript", lines=5)

            gr.Markdown("### 📥 Download Promotional Clips")
            with gr.Row():
                # Display up to 3 clips for individual download
                clip_1 = gr.Audio(label="Clip 1: Hook", type="filepath")
                clip_2 = gr.Audio(label="Clip 2: Key Insight", type="filepath")
                clip_3 = gr.Audio(label="Clip 3: High Energy", type="filepath")

            def handle_output(audio):
                text, status, clips = process_podcast(audio)
                # Ensure we return a value for every output component
                while len(clips) < 3:
                    clips.append(None)
                return text, status, clips[0], clips[1], clips[2]

            process_btn.click(
                fn=handle_output, 
                inputs=audio_input, 
                outputs=[transcript_out, status_msg, clip_1, clip_2, clip_3]
            )
        # TAB 2: COPYRIGHT
        with gr.Tab("Copyright Check"):
            gr.Markdown("Compliance & AI Labeling")
            with gr.Row():
                copy_input = gr.Audio(label="Select Clip for Check", type="filepath")
                copy_btn = gr.Button("Verify Compliance")
            copy_output = gr.JSON(label="Legal Report")
            copy_btn.click(check_copyright, inputs=copy_input, outputs=copy_output)

demo.launch()